version: "3.8"

services:
  backend:
    image: registry.gitlab.com/amixsol1-group/1917/backend:latest
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/${DB_NAME}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}
      SPRING_ELASTICSEARCH_URIS: http://search:9200
    depends_on:
      db:
        condition: service_healthy
      search:
        condition: service_healthy
    healthcheck:
      # НЕ нужен wget/curl: проверяем HTTP через bash + /dev/tcp
      test:
        [
          "CMD-SHELL",
          "bash -c 'exec 3<>/dev/tcp/127.0.0.1/8080 && echo -e \"GET /actuator/health HTTP/1.1\\r\\nHost: localhost\\r\\nConnection: close\\r\\n\\r\\n\" >&3 && cat <&3 | grep -q UP'"
        ]
      interval: 10s
      timeout: 5s
      retries: 30
      start_period: 30s
    networks: [shop-net]

  haproxy:
    image: haproxy:2.9
    container_name: shop-haproxy
    restart: unless-stopped
    ports:
      - "80:8080"
      - "8404:8404"
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      backend:
        condition: service_healthy
    networks: [shop-net]

  frontend:
    image: registry.gitlab.com/amixsol1-group/1917/frontend:latest
    container_name: shop-frontend
    restart: unless-stopped
    depends_on:
      haproxy:
        condition: service_started
    networks: [shop-net]

  db:
    image: postgres:16.0
    container_name: shop-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks: [shop-net]

  search:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.22
    container_name: shop-search
    restart: unless-stopped
    environment:
      discovery.type: single-node
      # для твоей RAM лучше поменьше
      ES_JAVA_OPTS: "-Xms256m -Xmx256m"
    volumes:
      - es-data:/usr/share/elasticsearch/data
    healthcheck:
      # НЕ нужен wget/curl: проверяем HTTP через bash + /dev/tcp
      test:
        [
          "CMD-SHELL",
          "bash -c 'exec 3<>/dev/tcp/127.0.0.1/9200 && echo -e \"GET /_cluster/health HTTP/1.1\\r\\nHost: localhost\\r\\nConnection: close\\r\\n\\r\\n\" >&3 && cat <&3 | grep -qE \"\\\"status\\\":\\\"(green|yellow)\\\"\"'"
        ]
      interval: 10s
      timeout: 5s
      retries: 60
      start_period: 40s
    networks: [shop-net]

networks:
  shop-net:
    driver: bridge

volumes:
  db-data:
  es-data: